# Cross-compiling the CAPS native core for Windows x64 from macOS or Linux with MinGW-w64 (see packaging/BUILD.md).
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_Fortran_COMPILER x86_64-w64-mingw32-gfortran)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
# Homebrew's mingw-w64 (Apple silicon or Intel)
if(EXISTS /opt/homebrew/opt/mingw-w64/toolchain-x86_64)
  set(CMAKE_FIND_ROOT_PATH /opt/homebrew/opt/mingw-w64/toolchain-x86_64)
else()
  set(CMAKE_FIND_ROOT_PATH /usr/local/opt/mingw-w64/toolchain-x86_64)
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
