#!/usr/bin/env python3
"""Generates studio/CapsStudio/Themes/Icons.axaml from the design system's icon set (design/generator/lib.py ICONS):
every icon (24 × 24, stroked) becomes one StreamGeometry; circles, ellipses and rounded rectangles become arcs."""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "design", "generator"))
from lib import ICONS  # noqa: E402


def num(v):
    return f"{float(v):g}"


def ellipse(cx, cy, rx, ry):
    cx, cy, rx, ry = map(float, (cx, cy, rx, ry))
    return (f"M{num(cx - rx)},{num(cy)} A{num(rx)},{num(ry)} 0 1 0 {num(cx + rx)},{num(cy)} "
            f"A{num(rx)},{num(ry)} 0 1 0 {num(cx - rx)},{num(cy)} Z")


def rect(x, y, w, h, r):
    x, y, w, h, r = map(float, (x, y, w, h, r))
    if r <= 0:
        return f"M{num(x)},{num(y)} H{num(x + w)} V{num(y + h)} H{num(x)} Z"
    return (f"M{num(x + r)},{num(y)} H{num(x + w - r)} A{num(r)},{num(r)} 0 0 1 {num(x + w)},{num(y + r)} V{num(y + h - r)} "
            f"A{num(r)},{num(r)} 0 0 1 {num(x + w - r)},{num(y + h)} H{num(x + r)} A{num(r)},{num(r)} 0 0 1 {num(x)},{num(y + h - r)} "
            f"V{num(y + r)} A{num(r)},{num(r)} 0 0 1 {num(x + r)},{num(y)} Z")


def attrs(tag):
    return dict(re.findall(r'(\w+)="([^"]*)"', tag))


def to_path(svg):
    parts = []
    for m in re.finditer(r"<(path|circle|ellipse|rect|polyline|line)\b([^>]*)>", svg):
        kind, a = m.group(1), attrs(m.group(2))
        if kind == "path":
            parts.append(a["d"])
        elif kind == "circle":
            parts.append(ellipse(a["cx"], a["cy"], a["r"], a["r"]))
        elif kind == "ellipse":
            parts.append(ellipse(a["cx"], a["cy"], a["rx"], a["ry"]))
        elif kind == "rect":
            parts.append(rect(a.get("x", 0), a.get("y", 0), a["width"], a["height"], a.get("rx", 0)))
        elif kind == "line":
            parts.append(f"M{a['x1']},{a['y1']} L{a['x2']},{a['y2']}")
        elif kind == "polyline":
            pts = a["points"].split()
            parts.append("M" + " L".join(pts))
    return " ".join(parts)


out = ['<!-- Generated by studio/tools/make_icons.py from design/generator/lib.py (ICONS). Do not edit. -->',
       '<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">']
for name, svg in ICONS.items():
    out.append(f'  <StreamGeometry x:Key="Icon.{name}">{to_path(svg)}</StreamGeometry>')
out.append('</ResourceDictionary>')
dest = os.path.join(ROOT, "studio", "CapsStudio", "Themes", "Icons.axaml")
os.makedirs(os.path.dirname(dest), exist_ok=True)
open(dest, "w").write("\n".join(out) + "\n")
print(f"wrote {len(ICONS)} icons to {dest}")
