"""Export the local mirror of the CAPS design canvas to the repository's design/ folder."""
import json, os, shutil, html, glob

SRC = os.path.dirname(os.path.abspath(__file__))
DST = os.environ.get("CAPS_DESIGN_DIR", os.path.normpath(os.path.join(SRC, "..")))
c = json.load(open(os.path.join(SRC, "project", "canvas.json")))
os.makedirs(os.path.join(DST, "boards"), exist_ok=True)
os.makedirs(os.path.join(DST, "generator"), exist_ok=True)
for b in c["order"]:
    shutil.copy2(os.path.join(SRC, "project", b), os.path.join(DST, "boards", b))
shutil.copy2(os.path.join(SRC, "project", "canvas.json"), os.path.join(DST, "canvas.json"))
for f in glob.glob(os.path.join(SRC, "*.py")):
    shutil.copy2(f, os.path.join(DST, "generator", os.path.basename(f)))

# group boards by the row title above them
titles = sorted([(n["y"], n["text"]) for k, n in c["notes"].items() if n.get("kind") == "title1"])
def row_of(y):
    t = [txt for ty, txt in titles if ty < y]
    return t[-1] if t else "Boards"
groups = {}
for b in c["order"]:
    info = c["boards"][b]
    groups.setdefault((row_of(info["y"])), []).append((b, info))
order = [txt for _, txt in titles if txt in groups]

cards = []
for g in order:
    items = []
    for b, info in groups[g]:
        w, h = info["w"], info["h"]
        s = 320 / w
        items.append(f'<a class="card" href="boards/{b}" target="_blank"><div class="thumb" style="height:{h * s:.0f}px"><iframe src="boards/{b}" loading="lazy" tabindex="-1" '
                     f'style="width:{w}px;height:{h}px;transform:scale({s:.5f})"></iframe></div><span>{html.escape(info["title"])}</span></a>')
    cards.append(f'<section><h2>{html.escape(g)}</h2><div class="grid">{"".join(items)}</div></section>')
page = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>CAPS design boards</title>
<style>
:root {{ --bg:#0F1113; --panel:#16191C; --line:#2C3137; --text:#E8E6E1; --muted:#A5ABB1; --acc:#F0A83C; }}
@media (prefers-color-scheme: light) {{ :root {{ --bg:#F4F2EE; --panel:#FFFFFF; --line:#D9D5CE; --text:#1B1E21; --muted:#5A6066; --acc:#B26B00; }} }}
body {{ margin:0; background:var(--bg); color:var(--text); font:14px/1.5 system-ui, sans-serif; }}
header {{ padding:32px 32px 8px; }} h1 {{ margin:0; font-size:24px; }} header p {{ margin:6px 0 0; color:var(--muted); max-width:760px; }}
section {{ padding:16px 32px; }} h2 {{ font-size:15px; margin:12px 0; color:var(--muted); font-weight:600; }}
.grid {{ display:grid; grid-template-columns:repeat(auto-fill, minmax(320px, 1fr)); gap:18px; }}
.card {{ display:flex; flex-direction:column; gap:8px; color:var(--text); text-decoration:none; }}
.card:hover span {{ color:var(--acc); }}
.thumb {{ width:320px; overflow:hidden; border:1px solid var(--line); border-radius:8px; background:var(--panel); position:relative; }}
.thumb iframe {{ border:0; transform-origin:0 0; pointer-events:none; position:absolute; left:0; top:0; }}
</style></head><body>
<header><h1>CAPS design boards</h1><p>{len(c["order"])} boards exported from the Design canvas. Open any board full size (1440 × 900). Layout: canvas.json. The boards are regenerated by the scripts in generator/ (Python 3, no dependencies).</p></header>
{"".join(cards)}
</body></html>"""
open(os.path.join(DST, "index.html"), "w").write(page)
print("exported", len(c["order"]), "boards to", DST)
